<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Service;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $service
     * @param $uid
     * @return Service||null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function isAllow($service, $uid)
    {
        return $this->createQueryBuilder('s')
        ->innerJoin("s.users", "u")
        ->where('u.id = :user')
        ->andWhere('s.id = :service')
        ->setParameter('user', $uid)
        ->setParameter("service", $service)
        ->setMaxResults(1)
        ->getQuery()
        ->getOneOrNullResult();
    }
}
