<?php

namespace AppBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function isAllow($uid)
    {
        return $this->createQueryBuilder('s')
        ->innerJoin('s.users', 'u')
        ->where('u.uid = :user')
        ->setParameter('user', $uid)
        ->setMaxResults(1)
        ->getQuery()
        ->getOneOrNullResult();
    }
}
