security:
    providers:
        cas:
            id: prayno.cas_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - cas.enabler.authenticator

    access_control:
        - { path: ^/, roles: ROLE_USER }
