parameters:
  host: perso-etudiant.u-pem.fr
  host.base_url: /~vrasquie/cas
  keys.dir: /../var/keys/

  ldap.host: ldap://vmldapetud1.u-pem.fr/
  ldap.fake.user:
        homedirectory:
          - /home/6ir1/test
        givenname:
          - test
        sn:
          - test
        uid:
          - test
        mail:
          - test@test.fr
        supannetuid:
          - 424242
        accountstatus:
          - true
  ldap.class:
      6ir1: Esipe - Informatique et Reseaux - 1

  cas.fake.user:
      user: test

  cas.enabler.auth:
      username_attribute: user
      query_service_parameter: service
      query_ticket_parameter: ticket
      options:
          env: "%kernel.environment%"
          default_user: "%cas.fake.user%"
          host: "%host%"
          base_url: "%host.base_url%"
      server_login_url: https://cas.u-pem.fr/login
      server_validation_url: https://cas.u-pem.fr/serviceValidate
      server_logout_url: https://cas.u-pem.fr/logout
      xml_namespace: cas

services:
  ldap.service:
      class: AppBundle\Service\LdapService
      arguments: ["%ldap.host%", "%kernel.environment%", "%ldap.fake.user%"]
  
  response.service:
      class: AppBundle\Service\ResponseService
  
  rsakey.service:
      class: AppBundle\Service\RSAKeyService
      arguments: ["%kernel.root_dir%", "%keys.dir%", "%master.passphrase%"]

  jwt.service:
      class: AppBundle\Service\JWTService
      arguments: ["@rsakey.service", "%host%"]

  uid.service:
      class: AppBundle\Service\UIDService

  user.service:
      class: AppBundle\Service\UserService
      arguments: ["@doctrine.orm.entity_manager", "@ldap.service", "%ldap.class%"]

  cas.enabler.authenticator:
      class: AppBundle\Security\CasEnablerAuthenticator
      arguments: ["%cas.enabler.auth%"]

  router.listener:
      class: AppBundle\EventListener\RouterListener
      arguments: ["%host.base_url%", "%kernel.environment%"]
      tags:
          - { name: kernel.event_subscriber }
