parameters:
  ldap_host: ldap://vmldapetud1.u-pem.fr/
  base_url: /~vrasquie/cas

  class_mapping:
      6ir1: Esipe/Informatique et Réseaux 1

  fake_ldap_user:
      homedirectory:
        - /home/6ir1/test
      givenname:
        - test
      sn:
        - test
      uid:
        - test
      mail:
        - test@test.fr
      supannetuid:
        - 424242
      accountstatus:
        - true

  fake_user: 
      user: test

  cas_enabler_auth:
      username_attribute: user
      query_service_parameter: service
      query_ticket_parameter: ticket
      options:
          env: "%kernel.environment%"
          default_user: "%fake_user%"
      server_login_url: https://cas.u-pem.fr/login
      server_validation_url: https://cas.u-pem.fr/serviceValidate
      server_logout_url: https://cas.u-pem.fr/logout
      xml_namespace: cas

services:
  ldap.service:
      class: AppBundle\Service\LdapService
      arguments: ["%ldap_host%", "%kernel.environment%", "%fake_ldap_user%"]
  
  response.service:
      class: AppBundle\Service\ResponseService

  flush.service:
      class: AppBundle\Service\FlushService

  user.service:
      class: AppBundle\Service\UserService
      arguments: ["@doctrine.orm.entity_manager", "@ldap.service", "%class_mapping%"]

  service.service:
      class: AppBundle\Service\ServiceService

  jwt.service:
      class: AppBundle\Service\JWTService
      arguments: ["%private.key.path%", "%private.key.passphrase%", "%public.key.path%"]

  cas.enabler.authenticator:
      class: AppBundle\Security\CasEnablerAuthenticator
      arguments: ["%cas_enabler_auth%"]

  router.listener:
      class: AppBundle\EventListener\RouterListener
      arguments: ["%base_url%", "%kernel.environment%"]
      tags:
          - { name: kernel.event_subscriber }
