parameters:
  env: dev
  host: perso-etudiant.u-pem.fr
  keys.dir: /../var/keys/

  ade.config:
    host: https://edt.u-pem.fr/jsp/webapi
    login: visuedt
    password: visuedt

  ldap.config:
    host: ldap://vmldapetud1.u-pem.fr/
    fake_user:
      homedirectory:
        - /home/6ir1/test
      givenname:
        - test
      sn:
        - test
      uid:
        - test
      mail:
        - test@test.fr
      supannetuid:
        - 424242
      accountstatus:
        - true

  cas.config:
    username_attribute: user
    query_service_parameter: service
    query_ticket_parameter: ticket
    options:
      env: "%env%"
      default_user:
        user: test
    server_login_url: https://cas.u-pem.fr/login
    server_validation_url: https://cas.u-pem.fr/serviceValidate
    server_logout_url: https://cas.u-pem.fr/logout
    xml_namespace: cas

  error_mapping:
    0: ~
    1: Not connected
    2: Token fatal error
    3: Undefined token
    4: Not valid token
    5: Unallowed token

services:
  ldap.service:
    class: AppBundle\Service\LdapService
    arguments: ["%ldap.config%", "%env%"]
  
  response.service:
    class: AppBundle\Service\ResponseService
    arguments: ["%error_mapping%"]
  
  rsakey.service:
    class: AppBundle\Service\RSAKeyService
    arguments: ["%kernel.root_dir%", "%keys.dir%", "%master.passphrase%"]

  jwt.service:
    class: AppBundle\Service\JWTService
    arguments: ["@rsakey.service", "%host%"]

  user.service:
    class: AppBundle\Service\UserService
    arguments: ["@doctrine.orm.entity_manager", "@ldap.service"]

  ade.service:
    class: AppBundle\Service\ADEService
    arguments: ["%ade.config%"]

  ade.adapter.service:
    class: AppBundle\Service\ADEAdapterService

  calendar.service:
    class: AppBundle\Service\CalendarService
    arguments: ["@ade.service", "@ade.adapter.service", "%kernel.root_dir%"]

  query.type:
    class: AppBundle\GraphQL\QueryType
    arguments: ["@calendar.service", "@jwt.service", "@user.service"]

  cas.enabler.authenticator:
    class: AppBundle\Security\CasEnablerAuthenticator
    arguments: ["%cas.config%"]
