# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  ldap.service:
      class: AppBundle\Service\LdapService
      arguments: ["%ldap_host%", "%env%"]
