parameters:
  ldap_host: ldap://vmldapetud1.u-pem.fr/
  host: perso-etudiant.u-pem.fr
  base_url: /~vrasquie/cas
  keys.dir: /../var/keys/

  class_mapping:
      6ir1: Esipe/Informatique et Réseaux 1

  fake_ldap_user:
      homedirectory:
        - /home/6ir1/test
      givenname:
        - test
      sn:
        - test
      uid:
        - test
      mail:
        - test@test.fr
      supannetuid:
        - 424242
      accountstatus:
        - true

  fake_user: 
      user: test

  cas_enabler_auth:
      username_attribute: user
      query_service_parameter: service
      query_ticket_parameter: ticket
      options:
          env: "%kernel.environment%"
          default_user: "%fake_user%"
          host: "%host%"
          base_url: "%base_url%"
      server_login_url: https://cas.u-pem.fr/login
      server_validation_url: https://cas.u-pem.fr/serviceValidate
      server_logout_url: https://cas.u-pem.fr/logout
      xml_namespace: cas

services:
  ldap.service:
      class: AppBundle\Service\LdapService
      arguments: ["%ldap_host%", "%kernel.environment%", "%fake_ldap_user%"]
  
  response.service:
      class: AppBundle\Service\ResponseService
  
  rsakey.service:
      class: AppBundle\Service\RSAKeyService
      arguments: ["%kernel.root_dir%", "%keys.dir%", "%keys.passphrase%"]

  jwt.service:
      class: AppBundle\Service\JWTService
      arguments: ["%kernel.root_dir%", "%keys.dir%", "%keys.passphrase%", "%host%"]

  user.service:
      class: AppBundle\Service\UserService
      arguments: ["@doctrine.orm.entity_manager", "@ldap.service", "%class_mapping%"]

  cas.enabler.authenticator:
      class: AppBundle\Security\CasEnablerAuthenticator
      arguments: ["%cas_enabler_auth%"]

  router.listener:
      class: AppBundle\EventListener\RouterListener
      arguments: ["%base_url%", "%kernel.environment%"]
      tags:
          - { name: kernel.event_subscriber }
