parameters:
  env: dev

  keys.dir: /../var/keys/
  host: perso-etudiant.u-pem.fr

  calendar.config:
    host: https://edt.u-pem.fr/jsp/webapi
    project_id: 19
    login: visuedt
    password: visuedt
    resources_mapping:
      ir1: 1640

  ldap.host: ldap://vmldapetud1.u-pem.fr/
  ldap.fake_user:
    homedirectory:
      - /home/6ir1/test
    givenname:
      - test
    sn:
      - test
    uid:
      - test
    mail:
      - test@test.fr
    supannetuid:
      - 424242
    accountstatus:
      - true
  ldap.class_mapping:
    6ir1: ir1

  cas.fake_user:
    user: test

  cas.enabler.auth:
    username_attribute: user
    query_service_parameter: service
    query_ticket_parameter: ticket
    options:
      env: "%env%"
      default_user: "%cas.fake_user%"
    server_login_url: https://cas.u-pem.fr/login
    server_validation_url: https://cas.u-pem.fr/serviceValidate
    server_logout_url: https://cas.u-pem.fr/logout
    xml_namespace: cas

  error_mapping:
    0: ~
    1: Not connected
    2: Token fatal error
    3: Undefined token
    4: Not valid token
    5: Unallowed token

services:
  ldap.service:
    class: AppBundle\Service\LdapService
    arguments: ["%ldap.host%", "%env%", "%ldap.fake_user%"]
  
  response.service:
    class: AppBundle\Service\ResponseService
    arguments: ["%error_mapping%"]
  
  rsakey.service:
    class: AppBundle\Service\RSAKeyService
    arguments: ["%kernel.root_dir%", "%keys.dir%", "%master.passphrase%"]

  jwt.service:
    class: AppBundle\Service\JWTService
    arguments: ["@rsakey.service", "%host%"]

  user.service:
    class: AppBundle\Service\UserService
    arguments: ["@doctrine.orm.entity_manager", "@ldap.service", "%ldap.class_mapping%"]

  calendar.service:
    class: AppBundle\Service\CalendarService
    arguments: ["%calendar.config%", "%kernel.root_dir%"]

  graphql.service:
    class: AppBundle\Service\GraphQLService
    arguments: ["@calendar.service", "@jwt.service", "@user.service"]

  cas.enabler.authenticator:
    class: AppBundle\Security\CasEnablerAuthenticator
    arguments: ["%cas.enabler.auth%"]
